import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{LayoutDashboard,UtensilsCrossed,Tags,PlusCircle,Settings,Store,Search,Plus,Pencil,Trash2,Eye,EyeOff,ChevronDown,X,Save,Image as ImageIcon,LogOut,ShoppingBag,RefreshCw}from"lucide-react";
import{createClient}from"@supabase/supabase-js";
import"./styles.css";

const supabase=createClient("https://hhucljglnepcieojszvf.supabase.co","sb_publishable_FyCR-wDLaj9jZjmNxqn_kQ_q8ZljzQT");

function Login({onAuth}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
const submit=async()=>{setBusy(true);setError("");try{const r=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(r.data.session)onAuth(r.data.session);else setError("Conta criada. Se o Supabase pedir confirmação, confirme o e-mail e depois entre.");}catch(e){setError(e?.message||"Não foi possível entrar.")}finally{setBusy(false)}};
return <div className="login-page"><div className="login-card"><Store size={32}/><h1>Painel Cardápio DDA</h1><p>{signup?"Crie o acesso administrativo.":"Entre para gerenciar a Delícia de Açaí."}</p><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)} /><button className="primary" onClick={submit} disabled={busy}>{busy?"Aguarde...":signup?"Criar acesso":"Entrar"}</button>{error&&<div className="login-error">{error}</div>}<button className="text-btn" onClick={()=>setSignup(!signup)}>{signup?"Já tenho acesso":"Criar primeiro acesso"}</button></div></div>}

function App(){const[session,setSession]=useState(null);useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
if(!session)return <Login onAuth={setSession}/>;return <Admin/>}

function Admin(){const[page,setPage]=useState("Dashboard"),[products,setProducts]=useState([]),[categories,setCategories]=useState([]),[addons,setAddons]=useState([]),[orders,setOrders]=useState([]),[search,setSearch]=useState(""),[modal,setModal]=useState(null),[loading,setLoading]=useState(true);
const load=async()=>{setLoading(true);const[p,c,a,o]=await Promise.all([supabase.from("menu_products").select("*").order("created_at"),supabase.from("menu_categories").select("*").order("created_at"),supabase.from("menu_addons").select("*").order("created_at"),supabase.from("orders").select("*,order_items(*)").order("created_at",{ascending:false}).limit(100)]);setProducts(p.data||[]);setCategories(c.data||[]);setAddons(a.data||[]);setOrders(o.data||[]);setLoading(false)};
useEffect(()=>{load();const ch=supabase.channel("dda-live").on("postgres_changes",{event:"*",schema:"public",table:"orders"},load).on("postgres_changes",{event:"*",schema:"public",table:"menu_products"},load).on("postgres_changes",{event:"*",schema:"public",table:"menu_categories"},load).on("postgres_changes",{event:"*",schema:"public",table:"menu_addons"},load).subscribe();return()=>{supabase.removeChannel(ch)}},[]);
const nav=[["Dashboard",LayoutDashboard],["Pedidos",ShoppingBag],["Produtos",UtensilsCrossed],["Categorias",Tags],["Adicionais",PlusCircle],["Configurações",Settings]];
const filtered=products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())||String(p.category_id||"").toLowerCase().includes(search.toLowerCase()));
return <div className="app"><aside><div className="brand"><Store/><div><strong>Painel Cardápio DDA</strong><small>Gestão do estabelecimento</small></div></div><nav>{nav.map(([l,I])=><button className={page===l?"active":""} onClick={()=>setPage(l)} key={l}><I size={18}/>{l}</button>)}</nav><div className="aside-foot">Cardápio conectado<br/><span>Delícia de Açaí</span></div><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut size={16}/>Sair</button></aside><main><header><div><span className="eyebrow">PAINEL ADMINISTRATIVO</span><h1>{page}</h1><p>{page==="Dashboard"?"Visão geral da operação.":page==="Pedidos"?"Pedidos recebidos pelo cardápio.":page==="Produtos"?"Cadastre, edite e controle a disponibilidade.":page==="Categorias"?"Organize os produtos em categorias.":page==="Adicionais"?"Gerencie complementos e preços.":"Configurações do estabelecimento."}</p></div><div className="status"><i/> Sistema conectado</div></header>{loading?<div className="panel">Carregando dados...</div>:page==="Dashboard"?<Dashboard products={products} orders={orders} setPage={setPage}/>:page==="Pedidos"?<Orders orders={orders} setOrders={setOrders}/>:page==="Produtos"?<Products products={filtered} search={search} setSearch={setSearch} categories={categories} reload={load} onAdd={()=>setModal({type:"product",data:null})} onEdit={p=>setModal({type:"product",data:p})}/>:page==="Categorias"?<Categories categories={categories} reload={load}/>:page==="Adicionais"?<Addons addons={addons} reload={load}/>:<SettingsPage/>}{modal?.type==="product"&&<ProductModal data={modal.data} categories={categories} onClose={()=>setModal(null)} reload={load}/>}</main></div>}

function Dashboard({products,orders,setPage}){const novos=orders.filter(o=>o.status==="novo").length;return <><section className="cards"><Stat label="Produtos" value={products.length} note="Cadastrados"/><Stat label="Pedidos novos" value={novos} note="Aguardando atendimento"/><Stat label="Pedidos hoje" value={orders.length} note="Últimos pedidos"/><Stat label="Ativos" value={products.filter(p=>p.active).length} note="Produtos disponíveis"/></section><section className="dash-grid"><div className="panel"><div className="panel-head"><div><h2>Pedidos recentes</h2><p>Atualização automática em tempo real</p></div><button className="text-btn" onClick={()=>setPage("Pedidos")}>Ver pedidos</button></div>{orders.slice(0,5).map(o=><div className="mini-row" key={o.id}><div className="thumb"><ShoppingBag size={18}/></div><div><strong>{o.customer_name}</strong><small>{new Date(o.created_at).toLocaleString("pt-BR")}</small></div><b>R$ {Number(o.total).toFixed(2).replace(".",",")}</b><span className="pill on">{o.status}</span></div>)}</div><div className="panel quick"><h2>Ações rápidas</h2><p>Gerencie o cardápio sem mexer no código.</p><button onClick={()=>setPage("Produtos")}><Plus size={17}/>Adicionar produto</button><button onClick={()=>setPage("Pedidos")}><ShoppingBag size={17}/>Ver pedidos</button><button onClick={location.reload}><RefreshCw size={17}/>Atualizar painel</button></div></section></>}
function Stat({label,value,note}){return <div className="stat"><span>{label}</span><b>{value}</b><small>{note}</small></div>}

function Orders({orders,setOrders}){const statusLabels={novo:"Novo",em_preparo:"Em preparo",pronto:"Pronto",saiu_entrega:"Saiu para entrega",concluido:"Concluído",cancelado:"Cancelado"};const change=async(id,status)=>{await supabase.from("orders").update({status,updated_at:new Date().toISOString()}).eq("id",id);setOrders(o=>o.map(x=>x.id===id?{...x,status}:x))};return <section className="panel"><div className="panel-head"><div><h2>Pedidos</h2><p>{orders.length} pedido(s) carregado(s)</p></div></div><div className="orders">{orders.map(o=><article className="order-card" key={o.id}><div className="order-head"><div><strong>{o.customer_name}</strong><small>{o.customer_phone} · {new Date(o.created_at).toLocaleString("pt-BR")}</small></div><b>R$ {Number(o.total).toFixed(2).replace(".",",")}</b></div><div className="order-items">{(o.order_items||[]).map(i=><div key={i.id}><strong>{i.quantity}x {i.product_name}</strong><span>{[i.size_label,i.flavor,i.syrup,...(i.fillings||[]),...(i.toppings||[]).map(t=>t.name||t)].filter(Boolean).join(" · ")}</span></div>)}</div><small>{o.street}, {o.number}{o.complement?", "+o.complement:""} — {o.neighborhood}, {o.city}</small><div className="order-actions"><select value={o.status} onChange={e=>change(o.id,e.target.value)}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><span className="pill on">{statusLabels[o.status]}</span></div></article>)}</div>{!orders.length&&<div className="empty">Nenhum pedido recebido ainda.</div>}</section>}

function Products({products,search,setSearch,categories,reload,onAdd,onEdit}){const toggle=async p=>{await supabase.from("menu_products").update({active:!p.active,updated_at:new Date().toISOString()}).eq("id",p.id);reload()};const remove=async id=>{if(confirm("Excluir este produto?")){await supabase.from("menu_products").delete().eq("id",id);reload()}};const cat=id=>categories.find(c=>c.id===id)?.name||id;return <section className="panel"><div className="panel-head"><div><h2>Produtos</h2><p>{products.length} produto(s) encontrado(s)</p></div><button className="primary" onClick={onAdd}><Plus size={17}/>Novo produto</button></div><div className="toolbar"><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar produto..."/></div><button className="filter">Todos <ChevronDown size={15}/></button></div><div className="table"><div className="thead"><span>Produto</span><span>Categoria</span><span>Preço</span><span>Status</span><span>Ações</span></div>{products.map(p=><div className="tr" key={p.id}><div className="product-cell"><div className="thumb"><ImageIcon size={18}/></div><div><strong>{p.name}</strong><small>{p.description}</small></div></div><span>{cat(p.category_id)}</span><strong>R$ {Number(p.base_price).toFixed(2).replace(".",",")}</strong><button className={p.active?"status-btn active":"status-btn"} onClick={()=>toggle(p)}>{p.active?<><Eye size={14}/>Ativo</>:<><EyeOff size={14}/>Oculto</>}</button><div className="actions"><button onClick={()=>onEdit(p)}><Pencil size={16}/></button><button onClick={()=>remove(p.id)}><Trash2 size={16}/></button></div></div>)}</div></section>}

function Categories({categories,reload}){const[name,setName]=useState(""),[emoji,setEmoji]=useState("🍇");const add=async()=>{if(!name.trim())return;await supabase.from("menu_categories").insert({id:name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-"),name:name.trim(),emoji});setName("");reload()};const del=async id=>{if(confirm("Excluir esta categoria?")){await supabase.from("menu_categories").delete().eq("id",id);reload()}};return <section className="panel"><div className="panel-head"><div><h2>Categorias</h2><p>Gerencie categorias do cardápio.</p></div></div><div className="inline-form"><input value={emoji} onChange={e=>setEmoji(e.target.value)} placeholder="🍇"/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nova categoria"/><button className="primary" onClick={add}><Plus size={17}/>Adicionar</button></div><div className="list">{categories.map(c=><div className="list-row" key={c.id}><div><Tags size={18}/><strong>{c.emoji} {c.name}</strong></div><button onClick={()=>del(c.id)}><Trash2 size={16}/></button></div>)}</div></section>}

function Addons({addons,reload}){const[name,setName]=useState(""),[price,setPrice]=useState("");const add=async()=>{if(!name.trim())return;const id=name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-")+"-"+Date.now();await supabase.from("menu_addons").insert({id,name:name.trim(),price:Number(price.replace(",","."))||0});setName("");setPrice("");reload()};const del=async id=>{await supabase.from("menu_addons").delete().eq("id",id);reload()};return <section className="panel"><div className="panel-head"><div><h2>Adicionais</h2><p>Cadastre complementos e seus preços.</p></div></div><div className="addon-form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do adicional"/><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Preço"/><button className="primary" onClick={add}><Plus size={17}/>Adicionar</button></div><div className="list">{addons.map(a=><div className="list-row" key={a.id}><div><PlusCircle size={18}/><strong>{a.name}</strong></div><div><b>R$ {Number(a.price).toFixed(2).replace(".",",")}</b><button onClick={()=>del(a.id)}><Trash2 size={16}/></button></div></div>)}</div></section>}

function ProductModal({data,categories,onClose,reload}){const[f,setF]=useState(data||{id:"produto-"+Date.now(),name:"",category_id:categories[0]?.id||"acai",base_price:0,description:"",active:true});const save=async()=>{const payload={id:f.id,name:f.name.trim(),category_id:f.category_id,base_price:Number(String(f.base_price).replace(",","."))||0,description:f.description||"",active:f.active!==false,updated_at:new Date().toISOString()};await supabase.from("menu_products").upsert(payload);reload();onClose()};return <div className="overlay"><div className="modal"><div className="modal-head"><div><h2>{data?"Editar produto":"Novo produto"}</h2><p>Altere os dados que serão usados pelo DDA.</p></div><button onClick={onClose}><X/></button></div><label>Nome<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><div className="two"><label>Categoria<select value={f.category_id} onChange={e=>setF({...f,category_id:e.target.value})}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Preço base<input value={f.base_price} onChange={e=>setF({...f,base_price:e.target.value})}/></label></div><label>Descrição<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><div className="modal-actions"><button className="ghost" onClick={onClose}>Cancelar</button><button className="primary" onClick={save}><Save size={17}/>Salvar</button></div></div></div>}

function SettingsPage(){return <section className="panel settings"><h2>Configurações do estabelecimento</h2><p>A integração com o cardápio está ativa.</p><div className="mini-row"><strong>Delícia de Açaí</strong><span className="pill on">Conectado ao Supabase</span></div><p>Os pedidos enviados pelo cardápio entram automaticamente na aba Pedidos.</p></section>}
function create(){createRoot(document.getElementById("root")).render(<App/>)}create();